name: Deploy to Fly

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - fly.toml
      - config/**
      - scripts/**

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.121
      - uses:  mdgreenwald/mozilla-sops-action@v1.4.1
        with:
          version: 3.8.1
      - name: Deploy app
        run: |
          flyctl deploy --remote-only -a $FLY_APP
        env:
          FLY_APP: ${{ secrets.FLY_APP }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
