name: Set secrets
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .config.env

jobs:
  deploy:
    name: Set secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 0.1.121
      - uses:  mdgreenwald/mozilla-sops-action@v1.4.1
        with:
          version: 3.8.1
      - name: Deploy app
        run: |
          sops --decrypt .config.env | flyctl secrets import -a $FLY_APP
        env:
          FLY_APP: ${{ secrets.FLY_APP }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
